# Generated by Django 5.1.4 on 2025-02-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_rename_creaed_orderdetail_created'),
    ]

    operations = [
    ]
